---
- name: Check if containers are already built
  command: "lxc-info -n {{ container_name }}"
  register: container_exists
  changed_when: false
  failed_when: >
    'exist' not in container_exists.stderr and
    'Name' not in container_exists.stdout
  args:
    warn: False

- name: Build LXC containers
  command: |
    lxc-create --name "{{ container_name }}" \
    --template "{{ lxc_template }}" \
    -- "{{ lxc_extra_args }}"
  when: container_exists.rc != 0
  args:
    warn: False
  tags:
    - build_lxc

- name: Ensure .ssh exists in container
  file:
    state: directory
    dest: "/var/lib/lxc/{{ container_name }}/rootfs/root/.ssh"
    owner: root
    group: root
    mode: 0700

- name: Drop root public key into container
  lineinfile:
    line: "{{ public_ssh_key }}"
    dest: "/var/lib/lxc/{{ container_name }}/rootfs/root/.ssh/authorized_keys"
    create: true

- name: Drop veth configurations
  blockinfile:
    dest: "/var/lib/lxc/{{ container_name }}/config"
    content: "{{ lookup('template', 'container-interface.ini.j2') }}"
    state: present
