---
- name: Check if containers are already built
  command: "lxc-info -n {{ container_name }}"
  register: container_exists
  changed_when: false
  failed_when: >
    'exist' not in container_exists.stderr and
    'Name' not in container_exists.stdout
  args:
    warn: False

- name: Merge lxc_options dict
  set_fact:
    lxc_arguments: > 
      {{ '--template='+lxc_options.lxc_template }}
      {{ '--vgname '+lxc_options.lxc_vgname if lxc_options.lxc_vgname is defined else '' }}
      {{ '--bdev '+lxc_options.lxc_backend if lxc_options.lxc_backend != 'file' else '' }}
      {{ '-- '+lxc_options.lxc_extra_args if lxc_options.lxc_extra_args is defined else '' }}

- name: Build LXC containers
  command: |
    lxc-create --name "{{ container_name }}" \
    "{{ lxc_arguments | regex_replace('\n','') | trim }}"
  when: container_exists.rc != 0
  args:
    warn: False
  tags:
    - build_lxc

- name: Drop veth configurations
  blockinfile:
    dest: "/var/lib/lxc/{{ container_name }}/config"
    content: "{{ lookup('template', 'container-interface.ini.j2') }}"
    state: present
