---
- name: Check if container is running
  command: "lxc-info -n {{ container_name }}"
  register: lxc_container_check
  changed_when: false

- name: Start LXC containers
  command: "lxc-start --name {{ container_name }}"
  when: lxc_container_check.rc != 0

- name: Wait for SSH
  wait_for:
    port: 22
    delay: 10
    timeout: 60
