---
dependency:
  name: galaxy
driver:
  name: vagrant
  ssh_connection_options:
      - -o UserKnownHostsFile=/dev/null
      - -o ControlMaster=auto
      - -o ControlPersist=60s
      - -o IdentitiesOnly=yes
      - -o StrictHostKeyChecking=no
      - -o ControlPath=~/.ansible/cp/%r@%h-%p

platforms:
  - name: centos7
    box: centos/7
providers:
  - name: libvirt
    type: libvirt
    options:
      memory: 512
      cpus: 1
instances:
  - name: "lxc-container_create"
    ansible_groups:
      - group1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
